### ISSUE TITLE
Feature Request: Allow project root and .git root to differ

### ISSUE THREAD

**Issue by asos-edgeorge** [BambooAppsDevTeam/GitHookPlugin#1]
Thanks for creating a really useful plugin, however, this doesn't seem to work in scenarios where the project root and `.git` root differ

For example:

```
.
└── root-folder/
    ├── scripts/
    │   └── hooks
    ├── .git/
    │   └── hooks
    └── android-project-root/
        ├── app/
        │   ├── src/
        │   └── build.gradle
        └── build.gradle
```

If I have a repo with this structure and want to install hooks from `scripts/hooks` into `.git/hooks` I don't think the plugin correctly accounts for that

For example, setting this in my top-level `build.gradle` adds an empty `.git/hooks` folder in my `android-project-root` directory

```groovy
gitHooks {
    gitHooksDirectory = new File(rootDir, "../scripts/hooks/")
}
```

I think you might need to expose another param to allow the manual setting of the `.git` folder's location

**Comment by amv-bamboo** [comment]
Thank you for the suggestion! This option will be released in 1.1.0
